---
title: "p8105_hw3_xl2834"
author: "Xiaoyu Li"
date: "10/04/2020"
output: github_document
---

```{r setup}
library(tidyverse)
library(ggridges)
```

## Problem 1


## Problem 2

#### Tidy the dataset
```{r}
accel_df = read_csv(
  "./data/accel_data.csv") %>%
  janitor::clean_names() %>% 
  pivot_longer(
    activity_1:activity_1440,
    names_to = "activity",
    names_prefix = "activity_",
    values_to = "steps"
    ) %>% 
  mutate(steps = round(steps, digits = 2)) %>% 
  mutate(activity = as.integer(activity))
  mutate(day_type = case_when(
    day == c("Saturday", "Sunday") ~ "Weekend"
    day == c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday") ~ "Weekday"
    TRUE ~ ""))
```

#### Total activity for each day

```{r}
daily_activity_df = 
  accel_df %>% 
  group_by(day_id) %>% 
  summarize(
    daily_activity = sum(steps)
  )

```

#### Make a plot showing daily activities

daily?
```{r}
plot_accel = 
  accel_df %>% 
  group_by(day_id) %>% 
  summarize(
    daily_activity = sum(steps),
    day = day
  ) %>% 
  ggplot(aes(x = day_id, y = daily_activity, color = day)) +
  geom_point()
```

hour?
```{r}
hour_accel = 
  accel_df %>% 
  mutate(hour = activity / 6) %>% 
  mutate(hour = round(floor(hour)) + 1)

hour_accel %>% 
  group_by(hour) %>% 
  summarize(
    hour_activity = sum(steps),
    day = day
  ) %>% 
  ggplot(aes(x = hour, y = hour_activity, color = day)) +
  geom_point()
```

don't need to do any extra things?
```{r}
accel_df %>% 
  group_by(day_id) %>% 
  ggplot(aes(x = activity, y = steps, color = day)) +
  geom_point()
```

## Problem 3




